<?php

/**
 * @file
 * Contains themoviedb_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function themoviedb_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the themoviedb_import module.
    case 'help.page.themoviedb_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('themoviedb is a module created for import data from themoviedb.org website') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function themoviedb_import_theme() {
  return [
    'themoviedb_import' => [
      'render element' => 'children',
    ],
  ];
}
